### PR TITLE
Feature/sort Post

### PR DESCRIPTION
**Pull request by thunyathep**

### CODE REVIEW

**Comment by thunyathep** [comment]
@teamchz @sura1542 @aofattaporn @Balloii 

Can you review and merge PR of Balloii first , I'll update my branch local and push it back later.

**Review by aofattaporn — APPROVED** [review]
this code is so ez to understand !! thanks for this! LGTM

**Comment by aofattaporn** [comment]
I'm not sure you need to sort posts on the profile page ?
@thunyathep

**Comment by thunyathep** [comment]
> I'm not sure you need to sort posts on the profile page ? @thunyathep

I'm worry about config of Profile Page that Team doing

**Review by sura1542 — APPROVED** [review]

**Pull request merged**
